name: Lint Code

on:
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort ruff pre-commit

    - name: Run linters
      run: |
        # Run all linters
        black --check src tests
        isort --check src tests
        ruff src tests